import type { AppData } from '../types'

const day = 24 * 60 * 60 * 1000
const now = Date.now()

/** Dane startowe pokazywane przy pierwszym uruchomieniu (i po "Wczytaj przykłady"). */
export function sampleData(): AppData {
  return {
    version: 1,
    folders: [
      { id: 'f-praca', name: 'Praca', emoji: '💼', createdAt: now - 30 * day },
      { id: 'f-dom', name: 'Dom', emoji: '🏠', createdAt: now - 25 * day },
      { id: 'f-pomysly', name: 'Pomysły', emoji: '💡', createdAt: now - 20 * day },
    ],
    notes: [
      {
        id: 'n-1',
        title: 'Plan tygodnia',
        body: [
          '## Priorytety',
          '',
          '- Skończyć **prezentację** dla klienta',
          '- Przegląd budżetu na Q3',
          '- Umówić przegląd auta',
          '',
          '> Najpierw rzeczy trudne, potem przyjemne.',
          '',
          '#planowanie',
        ].join('\n'),
        folderId: 'f-praca',
        tags: ['planowanie', 'tydzien'],
        color: 'blue',
        pinned: true,
        archived: false,
        trashed: false,
        checklist: [
          { id: 'c-1', text: 'Zebrać dane do prezentacji', done: true },
          { id: 'c-2', text: 'Zrobić szkic slajdów', done: true },
          { id: 'c-3', text: 'Wysłać do akceptacji', done: false },
        ],
        createdAt: now - 6 * day,
        updatedAt: now - 2 * 60 * 60 * 1000,
      },
      {
        id: 'n-2',
        title: 'Zakupy',
        body: 'Sobotni wypad do sklepu. Sprawdzić promocje na kawę.',
        folderId: 'f-dom',
        tags: ['zakupy'],
        color: 'green',
        pinned: true,
        archived: false,
        trashed: false,
        checklist: [
          { id: 'c-4', text: 'Chleb', done: false },
          { id: 'c-5', text: 'Kawa ziarnista', done: false },
          { id: 'c-6', text: 'Mleko owsiane', done: true },
          { id: 'c-7', text: 'Pomidory', done: false },
        ],
        createdAt: now - 3 * day,
        updatedAt: now - 20 * 60 * 1000,
      },
      {
        id: 'n-3',
        title: 'Pomysł: aplikacja do nawyków',
        body: [
          'Prosty tracker nawyków bez konta i bez chmury.',
          '',
          '### Założenia',
          '',
          '1. Jeden ekran, zero konfiguracji',
          '2. Seria dni jako główna motywacja',
          '3. Eksport do `JSON`',
          '',
          'Inspiracja: [Streaks](https://streaksapp.com)',
        ].join('\n'),
        folderId: 'f-pomysly',
        tags: ['produkt', 'szkic'],
        color: 'purple',
        pinned: false,
        archived: false,
        trashed: false,
        checklist: [],
        createdAt: now - 12 * day,
        updatedAt: now - 4 * day,
      },
      {
        id: 'n-4',
        title: 'Notatki ze spotkania 12.06',
        body: [
          'Ustalenia z zespołem:',
          '',
          '- deadline przesunięty o tydzień',
          '- Ania przejmuje kontakt z podwykonawcą',
          '- kolejny status w poniedziałek',
        ].join('\n'),
        folderId: 'f-praca',
        tags: ['spotkania'],
        color: 'yellow',
        pinned: false,
        archived: false,
        trashed: false,
        checklist: [],
        createdAt: now - 9 * day,
        updatedAt: now - 9 * day,
      },
      {
        id: 'n-5',
        title: 'Książki do przeczytania',
        body: '- Thinking in Systems\n- Zen i sztuka oporządzania motocykla\n- Atomowe nawyki',
        folderId: null,
        tags: ['ksiazki', 'na-potem'],
        color: 'orange',
        pinned: false,
        archived: false,
        trashed: false,
        checklist: [],
        createdAt: now - 40 * day,
        updatedAt: now - 15 * day,
      },
      {
        id: 'n-6',
        title: 'Stare hasła do WiFi',
        body: 'Router wymieniony, notatka już niepotrzebna.',
        folderId: 'f-dom',
        tags: [],
        color: 'default',
        pinned: false,
        archived: true,
        trashed: false,
        checklist: [],
        createdAt: now - 120 * day,
        updatedAt: now - 60 * day,
      },
    ],
  }
}
